#!/bin/sh
# Recreates, byte for byte, the oracle cases used in REVIEW.md and PLAN.md.
# Usage: sh create-cases.sh <dest-dir>
set -e
DEST=${1:?usage: create-cases.sh <dest-dir>}
mkdir -p "$DEST/review" "$DEST/additions"
c() { printf '%s' "$2" | base64 -d > "$DEST/$1"; }
c review/01_url.ucl cGFja2FnZXNpdGU6IGh0dHA6Ly9wa2cuZnJlZWJzZC5vcmcvbGF0ZXN0
c review/02_brackets.ucl c3F1YXJldGVzdDogc29tZVtddmFsdWU=
c review/03_numword.ucl a2V5MjogMTIgdmFsdWUK
c review/04_percent.ucl eCB7IGFsbC1kZXBlbmRzOiBxdWVyeSAlZG4tJWR2LCB9
c review/05_backslash.ucl c3RyaW5nIHRoYXQgZW5kcyBpbiBzbGFzaFw=
c review/06_ms.ucl a2V5ID0gMTBtUw==
c review/07_hexdot.ucl ayA9IDB4ZGVhZGJlZWYuMQ==
c review/08_hexbad.ucl ayA9IDB4cmVhZGJlZWY=
c review/09_twonames.ucl c3ViIHRlc3RzdWIxIHRlc3RzdWIyIHsga2V5ID0gMSB9
c review/10_dupnested.ucl c2VjdGlvbiBmb28gYmFyIHsga2V5ID0gdmFsdWUgfQpzZWN0aW9uIGZvbyB7IGJhciA9IGxvbCB9
c review/11_slashslash.ucl Ly8gY29tbWVudAprZXkgPSAx
c review/12_0b.ucl a2V5ID0gMGIxMDEw
c review/13_0o.ucl a2V5ID0gMG83NTU=
c review/14_heredoc.ucl ayA9IDw8RU9ECmxpbmUxCmxpbmUyCkVPRAo=
c review/15_dollardollar.ucl ayA9ICIkJHRlc3Qi
c review/16_dollarplain.ucl ayA9ICIkbm8ke30kJHRlc3Qi
c review/17_multikey.ucl YSA9IDEKYSA9IDIKYSA9IDM=
c review/18_emptykey.ucl IiIgPSAx
c review/19_utf8key.ucl 0LrQu9GO0YcgPSDQt9C90LDRh9C10L3QuNC1
c review/20_arraynested.ucl ayA9IFtbMSwyXSxbMyw0XV0=
c review/21_objinarray.ucl ayA9IFt7YT0xfSx7Yj0yfV0=
c review/22_colonobj.ucl QUxJQVMgICA6IHsKICB4OiB5LAp9
c review/23_semicolon_in_str.ucl ayA9ICJ2YWx1ZTsi
c review/24_nosep_obj.ucl c2VjdGlvbiB7IGEgPSAxIH0=
c review/25_neg_time.ucl ayA9IC0xMHM=
c review/26_bigint.ucl ayA9IDkyMjMzNzIwMzY4NTQ3NzU4MDc=
c review/27_overflow.ucl ayA9IDk5OTk5OTk5OTk5OTk5OTk5OTk5
c review/28_true_bare.ucl ayA9IHRydWUKbCA9IHllcwptID0gb24KbiA9IG9mZg==
c review/29_dot_key.ucl YS5iID0gMQ==
c review/30_inline_comment.ucl ayA9IDEgIyB0cmFpbGluZw==
c additions/a01_plus_concat.ucl ayA9ICJhIiArICJiIg==
c additions/a02_bare_float_inside.ucl ayA9IGZvbyAxLjUwIGJhcg==
c additions/a03_two_strings.ucl ayA9ICJhIiAiYiI=
c additions/a04_unbraced_var.ucl ayA9ICIkQUJJL3gi
c additions/a05_braced_var.ucl ayA9ICIke0FCSX14Ig==
c additions/a06_bare_var.ucl ayA9ICR7QUJJfQ==
c additions/a07_value_trailing_comment.ucl ayA9IGhlbGxvIHdvcmxkICAgIyBj
c additions/a08_array_no_commas.ucl ayA9IFsxIDIgM10=
c additions/a09_array_objs_no_comma.ucl ayA9IFt7YT0xfSB7Yj0yfV0=
c additions/a10_numeric_key.ucl MTIza2V5ID0gMQ==
c additions/a11_dash_key.ucl a2V5LXdpdGgtZGFzaCA9IDE=
c additions/a12_bool_prefix.ucl ayA9IHRydWVfdmFsdWU=
c additions/a13_case_bool.ucl YSA9IFRSVUUKYiA9IFRydWUKYyA9IE5VTEwKZCA9IFllcw==
c additions/a14_float_kb.ucl ayA9IDEuNWti
c additions/a15_hex_suffix.ucl ayA9IDB4MTBr
c additions/a16_plus_num.ucl ayA9ICs1
c additions/a17_neg_inf.ucl ayA9IC1pbmY=
c additions/a18_empty_value.ucl ayA9IDs=
c additions/a19_key_only.ucl azs=
c additions/a20_raw_newline_dq.ucl ayA9ICJhCmIi
c additions/a21_space_before_suffix.ucl ayA9IDEwIHM=
c additions/a22_time_h.ucl ayA9IDJo
c additions/a23_time_w.ucl ayA9IDF3
c additions/a24_int_float_exp_suffix.ucl ayA9IDFlM2ti
c additions/a25_top_multi_brace.ucl e2E9MX0Ke2I9Mn0=
c additions/a26_implicit_after_brace.ucl YSB7IGIgPSAxIH0gYyA9IDI=
c additions/a27_nested_dup_in_braces.ucl dG9wIHsgcyBmb28gYmFyIHsgayA9IHYgfQpzIGZvbyB7IGJhciA9IGxvbCB9IH0=
c additions/a28_value_semicolon_space.ucl ayA9IGEgYiA7IGogPSBj
c additions/a29_single_quote_cont.ucl ayA9ICdhXApiJw==
c additions/a30_heredoc_empty.ucl ayA9IDw8RU9ECkVPRAo=
c additions/a31_heredoc_crlf.ucl ayA9IDw8RU9EDQp4DQpFT0QN
c additions/a32_key_colon_nospace.ucl azp2
c additions/a33_url_in_array.ucl ayA9IFtodHRwOi8vYS5iL2MsIHhd
c additions/a34_string_escape_slash.ucl ayA9ICJhXC9iIg==
c additions/a35_json_trailing_comma.ucl eyJhIjogMSx9
c additions/a36_bare_dollar.ucl ayA9ICQ=
c additions/a37_leading_dot_value.ucl ayA9IC41
c additions/a38_trailing_dot_num.ucl ayA9IDUu
c additions/a39_leading_zero.ucl ayA9IDAwNw==
c additions/a40_underscore_num.ucl ayA9IDFfMDAw
c additions/a41_nested_obj_semicolons.ucl YSB7IGIgeyBjID0gMTsgfTsgZCA9IDI7IH07
c additions/a42_key_quoted_single.ucl J2snID0gMQ==
c additions/a43_comment_in_value.ucl ayA9IGEvKmMqL2I=
c additions/a44_hash_in_value.ucl ayA9IGEjYg==
c additions/a45_eq_in_value.ucl ayA9IGE9Yg==
c additions/a46_colon_in_value.ucl ayA9IGE6Yg==
c additions/a47_brace_in_value.ucl ayA9IGF7Yg==
c additions/a48_ms_uppercase.ucl ayA9IDVNUw==
c additions/a49_min_upper.ucl ayA9IDVNSU4=
c additions/a50_b_suffix.ucl ayA9IDVi
c additions/v01_vars.ucl IyBWYXJpYWJsZXMKa2V5dmFyID0gIiRBQkl0ZXN0IjsKa2V5dmFyID0gIiR7QUJJfSRBQkkke0FCSX0keyRBQkl9IjsKa2V5dmFyID0gIiR7c29tZX0kbm8ke30kJHRlc3QkJCQkJCQkIjsKa2V5dmFyID0gIiRBQkkkJEFCSSQkJEFCSSQkJCQiOwo=
c additions/v02_explicit_then_scalar.ucl ayA9IFsxLDJdCmsgPSAzCg==
c additions/v03_prefix.ucl ayA9ICIke0FCSX0iCmogPSAkQUJJCm0gPSAiJEFCSSRBQkkiCm4gPSAiJHtBQklYfSIKbyA9ICIkQUJJWCIK
